In [73]:
import pandas as pd

In [74]:
## reading data

In [75]:
df = pd.read_csv('data.csv')

In [76]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0    102         0   60         -1           1              0
1     99         0   26          0          -1              0
2     91         1   86          0           0              1
3     87         0   54          0          -1              1
4     66         0   50          0          -1              0

In [77]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
145     74         1   24          0           0              0
146     83         1   78          1          -1              1
147    100         1   78          1           0              1
148    100         0   20          1          -1              1
149     68         1   54          1          -1              1

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fever          150 non-null    int64
 1   bodyPain       150 non-null    int64
 2   age            150 non-null    int64
 3   runnyNose      150 non-null    int64
 4   diffBreath     150 non-null    int64
 5   infectionProb  150 non-null    int64
dtypes: int64(6)
memory usage: 7.2 KB


In [79]:
df['diffBreath'].value_counts()

 0    77
-1    72
 1     1
Name: diffBreath, dtype: int64

In [80]:
df.describe()

fever    bodyPain         age   runnyNose  diffBreath  \
count  150.000000  150.000000  150.000000  150.000000  150.000000   
mean    81.413333    0.586667   59.153333    0.460000   -0.473333   
std     13.758798    0.494081   24.806293    0.513313    0.514184   
min     58.000000    0.000000   20.000000   -1.000000   -1.000000   
25%     70.000000    0.000000   37.000000    0.000000   -1.000000   
50%     80.000000    1.000000   57.000000    0.000000    0.000000   
75%     94.000000    1.000000   83.000000    1.000000    0.000000   
max    104.000000    1.000000   98.000000    1.000000    1.000000   

       infectionProb  
count     150.000000  
mean        0.486667  
std         0.501497  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [81]:
##Train test splitting

In [82]:
import numpy as np

In [83]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)* ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]


In [84]:
np.random.permutation(7)

array([5, 1, 3, 0, 2, 4, 6])

In [85]:
train,test= data_split(df,0.2)

In [86]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
22     100         1   41          1           0              1
15      73         1   31          0          -1              1
65      70         0   63          0           0              0
11      85         0   55          0           0              0
42      89         1   36          0          -1              1
..     ...       ...  ...        ...         ...            ...
71      62         0   86          1           0              1
106     78         0   39          0          -1              1
14      76         0   48          0           0              1
92      89         1   26          0          -1              1
102     79         1   42          1           0              0

[120 rows x 6 columns]

In [87]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
73      77         0   72          0          -1              1
18      99         1   79          0           0              0
118    100         1   95          0          -1              1
78      90         1   94          1          -1              0
76      98         0   42          1          -1              1
31     100         1   86          1           0              1
64      77         1   23          0           0              0
141     70         0   46          1          -1              0
68     102         1   98          0           0              1
82      91         0   35          0          -1              1
110     98         0   24          0           0              1
12      77         1   96          1           0              1
36      64         1   78          0          -1              1
9       71         0   25          0           0              0
19      80         1   98          1           0              1
56      76         0   54          0           0              0
104    103         0   97          1           0              0
69      84         1   97          0          -1              0
55      66         1   95          0          -1              1
132    102         0   46          0           0              1
29      72         1   95          1           0              1
127     58         1   35          1          -1              0
26      60         0   23          1          -1              1
128     76         1   37          0           0              1
131     84         1   57          1           0              1
145     74         1   24          0           0              0
108     90         0   49          1           0              1
143    100         0   80          1          -1              1
45      67         1   91          1          -1              0
30      74         1   44          0           0              0

In [88]:
x_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

x_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [89]:
y_train = train[['infectionProb']].to_numpy().reshape(120,)
y_test = test[['infectionProb']].to_numpy().reshape(30,)

In [90]:
y_test

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [91]:
y_train

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [92]:
y_test

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [95]:
infoProb=clf.predict_proba([[100,1,22,1,1]])[0][1]

In [72]:
infoProb

0.20840989147391764